/**
 * Created by marieschmidt on 1/27/16.
 */
var results = {
"sweetBloom":[
    {"firstname":"Marie",
         "lastname": "Schmidt",
         "aromaCom": "cherry,fruity,light",
         "aroma": 7,
         "acidityCom": "",
         "acidity": 5,
         "mouthfeelCom": "thin",
         "mouthfeel": 5,
         "flavourCom": "thin flavour",
         "flavour": 6,
         "aftertasteCom": "",
         "aftertaste": 7,
         "balance": "too thin",
         "cupperScore": -1,
         "score": 79},

    {"firstname":"Alex",
        "lastname": "Uribe",
        "aromaCom": "fruit/nut",
        "aroma": 7,
        "acidityCom": "too acidic/offensive",
        "acidity": 1,
        "mouthfeelCom": "feels ok",
        "mouthfeel": 5,
        "flavourCom": "",
        "flavour": 3,
        "aftertasteCom": "too acid",
        "aftertaste": 2,
        "balance": "acidy, yucky",
        "cupperScore": -3,
        "score": 65},

    {"firstname":"David",
        "lastname": "Zuluaga",
        "aromaCom": "milk chocolate",
        "aroma": "" ,
        "acidityCom": "",
        "acidity": 7,
        "mouthfeelCom": "",
        "mouthfeel": 8,
        "flavourCom": "",
        "flavour": 8,
        "aftertasteCom": "",
        "aftertaste": 8,
        "balance": "",
        "cupperScore": -1,
        "score": 80},

    {"firstname":"Craig",
        "lastname": "Martin",
        "aromaCom": "carmel, chocolate",
        "aroma": 6 ,
        "acidityCom": "",
        "acidity": 6,
        "mouthfeelCom": "",
        "mouthfeel": 8,
        "flavourCom": "",
        "flavour": 5,
        "aftertasteCom": "",
        "aftertaste": 6,
        "balance": "mild, not a lot of distinct flavors",
        "cupperScore": 0,
        "score": 81},

    {"firstname":"Doug",
        "lastname": "Melvin",
        "aromaCom": "nutty/cereal",
        "aroma": 8,
        "acidityCom": "low",
        "acidity": 8,
        "mouthfeelCom": "creamy",
        "mouthfeel": 8,
        "flavourCom": "mandarin orange, apricot",
        "flavour": 9,
        "aftertasteCom": "slightly bitter",
        "aftertaste": 7,
        "balance": "",
        "cupperScore": 3,
        "score": 93},

    {"firstname":"Keith",
        "lastname": "Nygaard",
        "aromaCom": "nutty, almond, roasty, carbon",
        "aroma": 5,
        "acidityCom": "",
        "acidity": 7,
        "mouthfeelCom": "",
        "mouthfeel": 7,
        "flavourCom": "woody",
        "flavour": 6,
        "aftertasteCom": "",
        "aftertaste": 7,
        "balance": "",
        "cupperScore": 3,
        "score": 85},

    {"firstname":"Walter",
        "lastname": "Schlosser",
        "aromaCom": "savory, leathery",
        "aroma": 7,
        "acidityCom": "",
        "acidity": 8,
        "mouthfeelCom": "",
        "mouthfeel": 9,
        "flavourCom": "coffee",
        "flavour": 7,
        "aftertasteCom": "burnt",
        "aftertaste": 6,
        "balance": "",
        "cupperScore": 2,
        "score": 89},

    {"firstname":"Justin",
        "lastname": "Tomlinson",
        "aromaCom": "deep balance, toast",
        "aroma": 8,
        "acidityCom": "medium",
        "acidity": 7,
        "mouthfeelCom": "light",
        "mouthfeel": 6,
        "flavourCom": "well rounded, a little weak",
        "flavour": 6,
        "aftertasteCom": "ashy",
        "aftertaste": 6,
        "balance": "",
        "cupperScore": -2,
        "score": 81},

    {"firstname":"Larry",
        "lastname": "Samuels",
        "aromaCom": "light, not overpowering, unspecific",
        "aroma": "",
        "acidityCom": "low",
        "acidity": 9,
        "mouthfeelCom": "spicy",
        "mouthfeel": 9,
        "flavourCom": "light and clean",
        "flavour": 8,
        "aftertasteCom": "none",
        "aftertaste": 9,
        "balance": "",
        "cupperScore": 4,
        "score": 89},

    {"firstname":"Govinda",
        "lastname": "Tamburino",
        "aromaCom": "dirt, burnt, carmel",
        "aroma": "",
        "acidityCom": "",
        "acidity": 8,
        "mouthfeelCom": "",
        "mouthfeel": 5,
        "flavourCom": "",
        "flavour": 9,
        "aftertasteCom": "",
        "aftertaste": 9,
        "balance": "",
        "cupperScore": 4,
        "score": 85}
],

    "ink":[
        {"firstname":"Marie",
            "lastname": "Schmidt",
            "aromaCom": "roasty, bold, chocolatey, sweet",
            "aroma": 9,
            "acidityCom": "mild",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "dark, roasty",
            "flavour": 8,
            "aftertasteCom": "nice flavor throughout",
            "aftertaste": 8,
            "balance": "loved it",
            "cupperScore": 3,
            "score": 92},

        {"firstname":"Alex",
            "lastname": "Uribe",
            "aromaCom": "nothing stand out - good",
            "aroma": 8,
            "acidityCom": "too much",
            "acidity": 7,
            "mouthfeelCom": "feels great",
            "mouthfeel": 8,
            "flavourCom": " sweet but acidic",
            "flavour": 6,
            "aftertasteCom": "sweet :)",
            "aftertaste": 7,
            "balance": "solid",
            "cupperScore": 1,
            "score": 84},

        {"firstname":"David",
            "lastname": "Zuluaga",
            "aromaCom": "nut grain",
            "aroma": "" ,
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 4,
            "score": 78},

        {"firstname":"Craig",
            "lastname": "Martin",
            "aromaCom": "dried wood, mild",
            "aroma": 5,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 5,
            "aftertasteCom": "",
            "aftertaste": 5,
            "balance": "overroasted, burnt",
            "cupperScore": -5,
            "score": 72},

        {"firstname":"Doug",
            "lastname": "Melvin",
            "aromaCom": "burnt/toast",
            "aroma": 6,
            "acidityCom": "non-existent",
            "acidity": 9,
            "mouthfeelCom": "velvet",
            "mouthfeel": 8,
            "flavourCom": "carbon/tobacco",
            "flavour": 7,
            "aftertasteCom": "neutral",
            "aftertaste": 8,
            "balance": "",
            "cupperScore": 3,
            "score": 91},

        {"firstname":"Keith",
            "lastname": "Nygaard",
            "aromaCom": "earthy, soil, roasty, carbon",
            "aroma": 4,
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 3,
            "score": 84},

        {"firstname":"Walter",
            "lastname": "Schlosser",
            "aromaCom": "chocolate, dark chocolate",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 9,
            "flavourCom": "coffee",
            "flavour": 7,
            "aftertasteCom": "chocolate",
            "aftertaste": 8,
            "balance": "",
            "cupperScore": 2,
            "score": 89},

        {"firstname":"Justin",
            "lastname": "Tomlinson",
            "aromaCom": "smoky, grassy, weak",
            "aroma": 6,
            "acidityCom": "mild",
            "acidity": 7,
            "mouthfeelCom": "thin/clean",
            "mouthfeel": 7,
            "flavourCom": "toast",
            "flavour": 6,
            "aftertasteCom": "mild",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 0,
            "score": 83},

        {"firstname":"Larry",
            "lastname": "Samuels",
            "aromaCom": "stronger",
            "aroma": "",
            "acidityCom": "low",
            "acidity": 9,
            "mouthfeelCom": "dirty",
            "mouthfeel": 5,
            "flavourCom": "bitter",
            "flavour": 7,
            "aftertasteCom": "none",
            "aftertaste": 9,
            "balance": "",
            "cupperScore": 3,
            "score": 83},

        {"firstname":"Govinda",
            "lastname": "Tamburino",
            "aromaCom": "rotten, cacoa nibs",
            "aroma": "",
            "acidityCom": "",
            "acidity": 5,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 3,
            "balance": "",
            "cupperScore": 0,
            "score": 69}
    ],

    "middleState":[
        {"firstname":"Marie",
            "lastname": "Schmidt",
            "aromaCom": "chocolate, citrus",
            "aroma": 6,
            "acidityCom": "nice acidity",
            "acidity": 8,
            "mouthfeelCom": "a bit thin",
            "mouthfeel": 6,
            "flavourCom": "overall good",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "good",
            "cupperScore": 1,
            "score": 85},

        {"firstname":"Alex",
            "lastname": "Uribe",
            "aromaCom": "chocolatey",
            "aroma": 7,
            "acidityCom": "",
            "acidity": 4,
            "mouthfeelCom": "",
            "mouthfeel": 4,
            "flavourCom": " acid",
            "flavour": 4,
            "aftertasteCom": "acid",
            "aftertaste": 4,
            "balance": "tastes like acidy water",
            "cupperScore": -1,
            "score": 72},

        {"firstname":"David",
            "lastname": "Zuluaga",
            "aromaCom": "nope",
            "aroma": "" ,
            "acidityCom": "",
            "acidity": 5,
            "mouthfeelCom": "",
            "mouthfeel": 6,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 2,
            "score": 75},

        {"firstname":"Craig",
            "lastname": "Martin",
            "aromaCom": "nutty, earthy",
            "aroma": 7,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 8,
            "balance": "enjoyed, smooth, well defined",
            "cupperScore": 3,
            "score": 90},

        {"firstname":"Doug",
            "lastname": "Melvin",
            "aromaCom": "fresh bread",
            "aroma": 8,
            "acidityCom": "low-mild",
            "acidity": 8,
            "mouthfeelCom": "tealike/slick",
            "mouthfeel": 6,
            "flavourCom": "burnt",
            "flavour": 5,
            "aftertasteCom": "sour/bitter",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 1,
            "score": 84},

        {"firstname":"Keith",
            "lastname": "Nygaard",
            "aromaCom": "earthy, soil, roasty, carbon",
            "aroma": 4,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 2,
            "score": 85},

        {"firstname":"Walter",
            "lastname": "Schlosser",
            "aromaCom": "very mild, dry",
            "aroma": 6,
            "acidityCom": "a little sour",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "fruity",
            "flavour": 9,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 4,
            "score": 89},

        {"firstname":"Justin",
            "lastname": "Tomlinson",
            "aromaCom": "mild, weak",
            "aroma": 5,
            "acidityCom": "a bit sharp",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 6,
            "flavourCom": "sweet & sour",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": -2,
            "score": 77},

        {"firstname":"Larry",
            "lastname": "Samuels",
            "aromaCom": "light sun and little sweet",
            "aroma": "",
            "acidityCom": "none",
            "acidity": 9,
            "mouthfeelCom": "fine",
            "mouthfeel": 9,
            "flavourCom": "weak",
            "flavour": 7,
            "aftertasteCom": "none",
            "aftertaste": 9,
            "balance": "",
            "cupperScore": 2,
            "score": 86},

        {"firstname":"Govinda",
            "lastname": "Tamburino",
            "aromaCom": "vegetal, bandage/mold",
            "aroma": "",
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 1,
            "score": 74}
    ],

    "huckleberry":[
        {"firstname":"Marie",
            "lastname": "Schmidt",
            "aromaCom": "mild, carmel, overripe fruit",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "a bit thin",
            "mouthfeel": 6,
            "flavourCom": "too acidic for my liking",
            "flavour": 7,
            "aftertasteCom": "lingering bitter",
            "aftertaste": 6,
            "balance": "bit acidic",
            "cupperScore": 0,
            "score": 81},

        {"firstname":"Alex",
            "lastname": "Uribe",
            "aromaCom": "",
            "aroma": 8,
            "acidityCom": "",
            "acidity": 5,
            "mouthfeelCom": "light",
            "mouthfeel": 4,
            "flavourCom": "",
            "flavour": 5,
            "aftertasteCom": "",
            "aftertaste": 4,
            "balance": "acid",
            "cupperScore": 5,
            "score": 81},

        {"firstname":"David",
            "lastname": "Zuluaga",
            "aromaCom": "stone fruit, berry",
            "aroma": "" ,
            "acidityCom": "",
            "acidity": 9,
            "mouthfeelCom": "",
            "mouthfeel": 9,
            "flavourCom": "",
            "flavour": 9,
            "aftertasteCom": "",
            "aftertaste": 9,
            "balance": "",
            "cupperScore": 5,
            "score": 91},

        {"firstname":"Craig",
            "lastname": "Martin",
            "aromaCom": "nutty, peanut, hazelnut",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "boring, mold chocolate",
            "cupperScore": 0,
            "score": 81},

        {"firstname":"Doug",
            "lastname": "Melvin",
            "aromaCom": "nutty/bread",
            "aroma": 6,
            "acidityCom": "mid-high",
            "acidity": 7,
            "mouthfeelCom": "2% milk",
            "mouthfeel": 8,
            "flavourCom": "toast/burnt",
            "flavour": 6,
            "aftertasteCom": "light bitter",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 2,
            "score": 86},

        {"firstname":"Keith",
            "lastname": "Nygaard",
            "aromaCom": "earthy, soil, roasty, carbon",
            "aroma": 4,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 2,
            "score": 86},

        {"firstname":"Walter",
            "lastname": "Schlosser",
            "aromaCom": "floral, burnt",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "berry",
            "flavour": 9,
            "aftertasteCom": "chocolate",
            "aftertaste": 9,
            "balance": "",
            "cupperScore": 4,
            "score": 94},

        {"firstname":"Justin",
            "lastname": "Tomlinson",
            "aromaCom": "top end, floral",
            "aroma": 6,
            "acidityCom": "mild",
            "acidity": 6,
            "mouthfeelCom": "rich",
            "mouthfeel": 8,
            "flavourCom": "mild, bread",
            "flavour": 6,
            "aftertasteCom": "nice, balanced",
            "aftertaste": 8,
            "balance": "",
            "cupperScore": 4,
            "score": 88},

        {"firstname":"Larry",
            "lastname": "Samuels",
            "aromaCom": "light",
            "aroma": "",
            "acidityCom": "low",
            "acidity": 9,
            "mouthfeelCom": "fine",
            "mouthfeel": 9,
            "flavourCom": "light",
            "flavour": 7,
            "aftertasteCom": "none",
            "aftertaste": 9,
            "balance": "",
            "cupperScore": 4,
            "score": 88},

        {"firstname":"Govinda",
            "lastname": "Tamburino",
            "aromaCom": "spicy",
            "aroma": "",
            "acidityCom": "",
            "acidity": 4,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 4,
            "aftertasteCom": "",
            "aftertaste": 4,
            "balance": "",
            "cupperScore": -1,
            "score": 66}
    ],

    "commonWealth":[
        {"firstname":"Marie",
            "lastname": "Schmidt",
            "aromaCom": "overripe fruit, floral, caramel",
            "aroma": 9,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 6,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "bit bitter",
            "aftertaste": 6,
            "balance": "bit bitter",
            "cupperScore": 0,
            "score": 85},

        {"firstname":"Alex",
            "lastname": "Uribe",
            "aromaCom": "good",
            "aroma": 7,
            "acidityCom": "",
            "acidity": 5,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 2,
            "aftertasteCom": "",
            "aftertaste": 5,
            "balance": "offended, tastes like dirty water",
            "cupperScore": -2,
            "score": 72},

        {"firstname":"David",
            "lastname": "Zuluaga",
            "aromaCom": "floral, citrus",
            "aroma": "" ,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 6,
            "flavourCom": "",
            "flavour": 8,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 4,
            "score": 83},

        {"firstname":"Craig",
            "lastname": "Martin",
            "aromaCom": "nut, floral, sweet",
            "aroma": 8,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 8,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "enjoyed, floral and sweet",
            "cupperScore": 3,
            "score": 91},

        {"firstname":"Doug",
            "lastname": "Melvin",
            "aromaCom": "floral/citrus, sweet",
            "aroma": 7,
            "acidityCom": "mid-high",
            "acidity": 8,
            "mouthfeelCom": "smooth/milky",
            "mouthfeel": 8,
            "flavourCom": "woody",
            "flavour": 7,
            "aftertasteCom": "butter",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 3,
            "score": 90},

        {"firstname":"Keith",
            "lastname": "Nygaard",
            "aromaCom": "cocoa",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 4,
            "score": 88},

        {"firstname":"Walter",
            "lastname": "Schlosser",
            "aromaCom": "fruity sweet, floral",
            "aroma": 8,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 9,
            "flavourCom": "",
            "flavour": 8,
            "aftertasteCom": "",
            "aftertaste": 7,
            "balance": "",
            "cupperScore": 4,
            "score": 93},

        {"firstname":"Justin",
            "lastname": "Tomlinson",
            "aromaCom": "fruity, distinct, sweet tea",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 6,
            "mouthfeelCom": "average",
            "mouthfeel": 6,
            "flavourCom": "herby",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 0,
            "score": 80},

        {"firstname":"Larry",
            "lastname": "Samuels",
            "aromaCom": "starbucks",
            "aroma": "",
            "acidityCom": "low",
            "acidity": 9,
            "mouthfeelCom": "dirty",
            "mouthfeel": 5,
            "flavourCom": "starbucks/dirt",
            "flavour": 5,
            "aftertasteCom": "still here",
            "aftertaste": 5,
            "balance": "",
            "cupperScore": 2,
            "score": 76},

        {"firstname":"Govinda",
            "lastname": "Tamburino",
            "aromaCom": "garlic, lemongrass, floral, raspberry",
            "aroma": "",
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 1,
            "score": 76}
    ],

    "boxcar":[
        {"firstname":"Marie",
            "lastname": "Schmidt",
            "aromaCom": "floral, tropical fruit",
            "aroma": 7,
            "acidityCom": "",
            "acidity": 5,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 5,
            "balance": "coffee was cold",
            "cupperScore": 0,
            "score": 80},

        {"firstname":"Alex",
            "lastname": "Uribe",
            "aromaCom": "",
            "aroma": "",
            "acidityCom": "",
            "acidity": "",
            "mouthfeelCom": "",
            "mouthfeel": "",
            "flavourCom": " ",
            "flavour": "",
            "aftertasteCom": "",
            "aftertaste": "",
            "balance": "",
            "cupperScore": "",
            "score": ""},

        {"firstname":"David",
            "lastname": "Zuluaga",
            "aromaCom": "earthy, grapefruit",
            "aroma": "" ,
            "acidityCom": "",
            "acidity": 7,
            "mouthfeelCom": "",
            "mouthfeel": 6,
            "flavourCom": "",
            "flavour": 8,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 2,
            "score": 79},

        {"firstname":"Craig",
            "lastname": "Martin",
            "aromaCom": "sweet, chocolate, caramel",
            "aroma": 7,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "",
            "flavour": 6,
            "aftertasteCom": "",
            "aftertaste": 8,
            "balance": "undertoned, savory, not offensive but not remarkable",
            "cupperScore": 2,
            "score": 88},

        {"firstname":"Doug",
            "lastname": "Melvin",
            "aromaCom": "fruit/chocolate, floral",
            "aroma": 9,
            "acidityCom": "low",
            "acidity": 8,
            "mouthfeelCom": "smooth",
            "mouthfeel": 8,
            "flavourCom": "toast",
            "flavour": 7,
            "aftertasteCom": "none",
            "aftertaste": 8,
            "balance": "",
            "cupperScore": 3,
            "score": 93},

        {"firstname":"Keith",
            "lastname": "Nygaard",
            "aromaCom": "nut",
            "aroma": 6,
            "acidityCom": "",
            "acidity": 8,
            "mouthfeelCom": "",
            "mouthfeel": 8,
            "flavourCom": "",
            "flavour": 7,
            "aftertasteCom": "",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 4,
            "score": 91},

        {"firstname":"Walter",
            "lastname": "Schlosser",
            "aromaCom": "fruity",
            "aroma": 8,
            "acidityCom": "",
            "acidity": 9,
            "mouthfeelCom": "",
            "mouthfeel": 7,
            "flavourCom": "fruity",
            "flavour": 8,
            "aftertasteCom": "burnt",
            "aftertaste": 5,
            "balance": "",
            "cupperScore": 3,
            "score": 90},

        {"firstname":"Justin",
            "lastname": "Tomlinson",
            "aromaCom": "rich, chocolatey",
            "aroma": 7,
            "acidityCom": "strong acidity",
            "acidity": 6,
            "mouthfeelCom": "medium-light",
            "mouthfeel": 7,
            "flavourCom": "full",
            "flavour": 7,
            "aftertasteCom": "long lingering chocolate",
            "aftertaste": 8,
            "balance": "",
            "cupperScore": 3,
            "score": 88},

        {"firstname":"Larry",
            "lastname": "Samuels",
            "aromaCom": "light",
            "aroma": "",
            "acidityCom": "low",
            "acidity": 9,
            "mouthfeelCom": "dirty",
            "mouthfeel": 5,
            "flavourCom": "yuck",
            "flavour": 5,
            "aftertasteCom": "better than E",
            "aftertaste": 6,
            "balance": "",
            "cupperScore": 2,
            "score": 77},

        {"firstname":"Govinda",
            "lastname": "Tamburino",
            "aromaCom": "savory, dried fruit, wood, carbon, acidic",
            "aroma": "",
            "acidityCom": "",
            "acidity": 3,
            "mouthfeelCom": "",
            "mouthfeel": 5,
            "flavourCom": "",
            "flavour": 4,
            "aftertasteCom": "",
            "aftertaste": 4,
            "balance": "",
            "cupperScore": 0,
            "score": 66}
    ]
};

/* Calculates Users Individual Scores */

/* Define function to check if entry is a number */
function checkNumber(x) {
    if (typeof(x)== "number") {
        return x
    }
    else {
        return 0
    }
}



// loop through roasters & individuals
for (var key in results) {
    var roasterName = results[key];

    // create results object to hold all scores
    roasterName.results = {
        aromaTotal: [],
        acidityTotal: [],
        mouthfeelTotal: [],
        flavourTotal: [],
        aftertasteTotal: [],
        cupperScoreTotal: [],
        scoreTotal: []
    };


    for (var prop = 0; prop < roasterName.length ; prop++) {
        var indivName = (roasterName[prop]);

        var aroma = checkNumber(indivName["aroma"]);
        roasterName.results.aromaTotal.push(aroma);

        var acidity = checkNumber(indivName["acidity"]);
        roasterName.results.acidityTotal.push(acidity);

        var mouthfeel = checkNumber(indivName["mouthfeel"]);
        roasterName.results.mouthfeelTotal.push(mouthfeel);

        var flavour = checkNumber(indivName["flavour"]);
        roasterName.results.flavourTotal.push(flavour);

        var aftertaste = checkNumber(indivName["aftertaste"]);
        roasterName.results.aftertasteTotal.push(aftertaste);

        var cupperScore = checkNumber(indivName["cupperScore"]);
        roasterName.results.cupperScoreTotal.push(cupperScore);

        indivName["score"] = aroma + acidity + mouthfeel + flavour + aftertaste + cupperScore + 50;
        roasterName.results.scoreTotal.push(indivName["score"])
    }

    console.log(roasterName.results)

    roasterName.average = {
        aromaAvg:0,
        acidityAvg: 0,
        mouthfeelAvg: 0,
        flavourAvg: 0,
        aftertasteAvg: 0,
        cupperScoreAvg: 0,
        scoreAvg: 0,
    };
}

